### ISSUE TITLE
provide performance and memory numbers for example programs

### ISSUE THREAD

**Issue by matu3ba** [arp242/lpeg.vim#1]
https://en.wikipedia.org/wiki/Parsing_expression_grammar#Advantages and the section on disadvantages writes "However, a PEG will require an amount of memory proportional to the length of the input".

**Comment by arp242** [comment]
This is something I worked on a bit last year, and I may or may not continue to work on it in the future. I put it here in case people are interested, but that's it.

Other than that, I don't really care about performance beyond "reasonably fast"; I'm not really interested in spending a lot of time on benchmarks and whatnot.
