### ISSUE TITLE
describe or link how ambiguity is resolved or checked

### ISSUE THREAD

**Issue by matu3ba** [arp242/lpeg.vim#2]
see https://en.wikipedia.org/wiki/Parsing_expression_grammar#Ambiguity_detection_and_influence_of_rule_order_on_language_that_is_matched

Maybe I missed it in the text.

**Comment by arp242** [comment]
I have no idea; as I mentioned in the other issue, it's just an experiment thingy so I'm not really keen to figure it all out.

And it should be documented on the LPeg library rather than here anyway, if it's not already: http://www.inf.puc-rio.br/~roberto/lpeg/
