### ISSUE TITLE
clarify license for grammar files

### ISSUE THREAD

**Issue by matu3ba** [arp242/lpeg.vim#3]
See in grammar files `-- Copyright 2020 Karchnu karchnu@karchnu.fr.`, which makes it very unclear what and how reusage is feasible.

**Comment by arp242** [comment]
From the LICENSE file:

> lexer/* contains the LPeg based lexers used for syntax highlighting, and are imported from the Scintillua project licensed under the MIT license. Check the individual source files for more specific copyright information.
