### ISSUE TITLE
more background on decision for treesitter

### ISSUE THREAD

**Issue by matu3ba** [arp242/lpeg.vim#4]
Treesitter gives
- language-independent parser (not only lexer) derivable from a DSL
- resistance to parsing failures
- S-expression storage format, which can be queried and modified by third party tools rather easily
- a runtime with query perf of something like `O(log(M))`
- fully incremental updates after initial construction
- ability to interface with your own parser implementation (although the interface is still unstable)

That said, treesitter is unsuitable from personal experience for
- code files with size > 500 LOC (mostly initial parsing time of DSL-derived parsers)
- anything that does heavy query (for example to find items with common semantics)

So all in all treesitter is a usable solution for script files or languages without a reusable parser.
However the most important contribution is to establish a common parser interface convention, which hopefully projects like rustsitter (https://github.com/hydro-project/rust-sitter) and custom runtime with better quer performance than `O(log(M))` will improve on.

In contrast to that are projects like `lpeg` more tailored to big sized files like what `tags` files are used for and more reliable than a `lsp`, which requires a pile of time for semantic analysis to resolve generics and caching etc.

**Comment by arp242** [comment]
https://github.com/arp242/lpeg.vim#rationale-and-history documents some stuff; I take it you already read that. I also wrote a bit over here, but it mostly repeats what's in the README: https://github.com/vim/vim/issues/9087#issuecomment-1146111454

I don't really have anything to add. I found treesitter awkward to use and it failed requirements 2 through 4.
